[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.13.0"
sea-orm = {version="2.0.0-rc", features = [
	"sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls", "macros",
	"schema-sync", "entity-registry"
	]}
utoipa-swagger-ui = {version="9.0.2", features=["actix-web"]}
utoipa = { version = "5.4.0", features = ["actix_extras", ] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
env_logger = "0.11.9"
rand = { version = "0.10.0", features = ["std"] }
sha2 = "0.10.9"
deadpool-redis = "0.23.0"
lettre = { version = "0.11.19", features = ["smtp-transport", "tokio1", "tokio1-native-tls"] }
