[package]
name = "gateway_service"
version = "0.1.0"
edition = "2021"

[dependencies]
pingora = "0.7"
pingora-core = "0.7"
pingora-proxy = "0.7"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
once_cell = "1.19"
bytes = "1.11.1"
pingora-http = "0.7.0"
actix-web = "4.13.0"
serde_yaml = "0.9.34"
serde = { version = "1.0.228", features = ["derive"] }
reqwest = { version = "0.13.2", features = ["blocking"] }

